services:
  - type: web
    name: mtg-deckbuilder
    env: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/MTGDeckBuilder-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: firebase.json