spring.application.name=MTGDeckBuilder
spring.redis.url=rediss://default:Abd1AAIjcDE2ZmEzYjA5MjEyZWI0YTM1OWQ4MzgzOWQ0ZmE2MTlkY3AxMA@happy-crayfish-46965.upstash.io:6379
spring.redis.host=happy-crayfish-46965.upstash.io
spring.redis.port=6379
string.redis.username=default
spring.redis.password=Ard1AAIgcDGn6tf2n3eG8Tr_tQR7_N7Hd1_96UYj06BO1i6qT4YWXA
spring.redis.ssl.enabled=true