spring.application.name=MTGDeckBuilder
spring.redis.host=happy-crayfish-46965.upstash.io
spring.redis.port=6379
spring.redis.password=Ard1AAIgcDGn6tf2n3eG8Tr_tQR7_N7Hd1_96UYj06BO1i6qT4YWXA
spring.redis.ssl=true